const ACTIONS_TYPES = {
    SET_SELECTED_ITEM: "SET_SELECTED_ITEM",
    ADD_NEW_ITEM: "ADD_NEW_ITEM",
    EDIT_NEW_ITEM: "EDIT_NEW_ITEM",
    DELTE_ITEM: "DELTE_ITEM",
    CLEAR_SELECTED_ITEM: "CLEAR_SELECTED_ITEM",
    UPDATE_ADD_NEW_ITEM_FLAG: "UPDATE_ADD_NEW_ITEM_FLAG",
    SET_SORT_BY_VALUE: "SET_SORT_BY_VALUE",
    SET_SEARCH_FIELD: "SET_SEARCH_FIELD"
}

export default ACTIONS_TYPES;